name: GitHub Pages
permissions:
  contents: read
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      deployments: write
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - name: Install documentation requirements
        run: |
          pip install -r docs/requirements.txt

      - name: Make docs builds
        run: |
          make -C docs html O="-t release"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
